name: Top Trumps Server CI
on:
  push:
    branches:
        - master
        - develop
        - sonarqube
  pull_request:
    branches:
        - master
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: pip install -r requirements.txt

    - name: Run tests
      run: coverage run -m unittest discover

    - name: Build docker image
      run: docker build . --file Dockerfile --tag top-trumps-server:$(date +%s)

    - name: Coveralls GitHub Action
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls

    - name: Sonar Cloud
      run: |
        export SONAR_SCANNER_VERSION=4.2.0.1873
        export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
        curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
        unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        export SONAR_SCANNER_OPTS="-server"

        sonar-scanner \
        -Dsonar.organization=kaushik-rohit \
        -Dsonar.projectKey=kaushik-rohit_top-trumps-server \
        -Dsonar.sources=./src \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=b9a72c92b9bff9fc4ecdad6b426a952403f9eab6
