name: Top Trumps Server CI
on:
  push:
    branches:
        - master
        - develop
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover

    - name: Build docker image
      run: docker build . --file Dockerfile --tag top-trumps-server:$(date +%s)
